# Generated by Django 6.0.4 on 2026-05-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
