# Generated by Django 6.0.4 on 2026-05-14 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_join_date_enrollment_roll_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Sheet mein jo naam aata hai (exact, case-insensitive match hogi)', max_length=200, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='students.course')),
            ],
            options={
                'verbose_name': 'Course Alias',
                'verbose_name_plural': 'Course Aliases',
                'ordering': ['alias'],
            },
        ),
    ]
