# Generated by Django 6.0.4 on 2026-05-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_coursealias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
