# Generated by Django 6.0.4 on 2026-05-06 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0004_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.enrollment'),
        ),
    ]
