# Generated by Django 6.0.4 on 2026-05-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_feestructure_feepayment_delete_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='month',
        ),
    ]
